### Lista de productos con paginación
GET http://127.0.0.1:8000/api/producto?page=1/limit=5&almacen=1
Authorization: Bearer 11|KfjN0f9mptbbdkG2Z7trl1YAcOuNBLSnYfV6PAGl304debce
Accept: application/json 


### Guardar Producto 
POST http://127.0.0.1:8000/api/producto 
Authorization: Bearer 11|KfjN0f9mptbbdkG2Z7trl1YAcOuNBLSnYfV6PAGl304debce
Accept: application/json 
Content-Type: application/json

{
"nombre": "Parlante", 
"descripcion": "Parlante gamer", 
"unidad_medida": "CAJA", 
"marca": "ASUS", 
"precio_venta": 500, 
"estado": true, 
"categoria_id": 1
}