### Lista de productos con paginación
GET http://127.0.0.1:8000/api/producto
Authorization: Bearer 8|c3geEecF1IEJiBvRD2CJ33655AZr1WiLW4bpL6kt7bfd2239
Accept: application/json 


### Guardar Producto 
POST http://127.0.0.1:8000/api/producto 
Authorization: Bearer 8|c3geEecF1IEJiBvRD2CJ33655AZr1WiLW4bpL6kt7bfd2239
Accept: application/json 
Content-Type: application/json

{
"nombre": "Parlante", 
"descripcion": "Parlante gamer", 
"unidad_medida": "CAJA", 
"marca": "ASUS", 
"precio_venta": 500, 
"estado": true, 
"categoria_id": 1
}