GET http://127.0.0.1:8000/api/usuario
Accept: application/json
Authorization: Bearer 4|XwMp2VN9TRUkjm12WnNw5wZKmerGGBnx9rgYLFvAf2af0f0c

### Guardar usuario
POST http://127.0.0.1:8000/api/usuario
Content-Type: application/json

{
  "name":"nuevo",
  "email":"nuevo@mail.com",
  "password": "nuevo12345"
}

### Mostrar usuario
GET http://127.0.0.1:8000/api/usuario/2

### Modificar
PUT http://127.0.0.1:8000/api/usuario/2
Accept: application/json
Content-Type: application/json

{
    "name": "juancho",
    "email": "juancho@mail.com",
    "password": "juan12345"
}

### Eliminar
DELETE http://127.0.0.1:8000/api/usuario/1
